### ISSUE TITLE
Profiles feature request

### ISSUE THREAD

**Issue by letkan** [KillerInk/FreeDcam#18]
Phone Model:Xiaomi Mi 4c LOS 14.1
---------------

FreeDcam Version:4.1beta6
-----------------
Is it possible to implement profiles, say one for black&white, one for jpeg high contrast, etc. so that one could switch to a set of custom settings by just one click?

**Comment by KillerInk** [comment]
Sorry i dont think thats a usefull feature. You can easy adjust saturation, contrast etc with the slider.
And depending on the scene you have to fine tune your profile.
Handling that stuff with profiles can get complicated because some devices dont support it, or use a special key.
Its not impossible, but i would never use it.
