### ISSUE TITLE
Bayer format is missing

### ISSUE THREAD

**Issue by knminhaz** [KillerInk/FreeDcam#52]
Phone Model: Huawei PRA-LX2
---------------

FreeDcam Version: 4.1 
beta9
-----------------

Problem Description:
--------------------
 I have a problem with weird tint in raw dng file. This tint does not go in post processing. The jpegs come out fine. I saw that changing the  bayer format to rggb can fix this. But that module is missing. What is the problem?

I shot in bayer format the used the freedcam gallery to convert bayer to dng. The resulting image had a lot of pink clippings.

https://imgur.com/a/7gHFxkv

**Comment by KillerInk** [comment]
Hi
its not the classic tint caused due wrong color pattern or blacklevel.
When you miss the "Bayer format" i expect you are on camera2.
For cam2 normaly a bayer is/was not needed because we trust in oems to implement it correct 🥇  

Clipping is the correct description for your problem. i think you have activated the freedcam converter.
cam2 returns ,equal wich bit depth the raw have, in 16bit. 
The freedcam converter think in that case the true data is 10bit and remove the 6 empty bits. 
in your case it seem that the data is 12bit and freedcam cut that two extra bit, wich results in clipped high/lights.
With the version you have, is the only way to turn off the freedcam converter and use the android DngCreator. it writes the full 16bit out.
