### ISSUE TITLE
Camera resets when selecting an option for NighOverlay or Horizontal Line while Preview PostProcessing is enabled

### ISSUE THREAD

**Issue by droped** [KillerInk/FreeDcam#57]
The camera runs the feature detector and resets all values when Preview PostProcessing is enabled and any option is selected in NightOverlay or Horizontal Line.

LG G3 d885  
Freedcam 4.1final (from github releases)  
Android 7.1.2

**Comment by KillerInk** [comment]
Hi,
i think you are using the legacy mode button, not the preview postprocessing one.
for legacy mode its needed to rerun the featuredetector, because, if support, the parameters from the camera change.
But you are right with the nightoverlay. it triggers the featuredetector. 
horizontal line seems total broken.
thx, i will look into it

**Comment by poutrosgit** [comment]
NightOverlay and Horizontal Line only seem to trigger feature detection and reset when PostProcessing is enabled. Without postprocessing enabled, they don't trigger it. I don't know if they actually work because I haven't tested it. It gets triggered when I was selecting off in those features but only with postprocessing enabled.
