### ISSUE TITLE
[Galaxy Note FE] App not listed as compatible despite being compatible

### ISSUE THREAD

**Issue by Cvolton** [KillerInk/FreeDcam#96]
Phone Model:
---------------
Samsung Galaxy S7 [herolte/SM-G930F] with a Samsung Galaxy Note FE [gracerlte/SM-N935F] ROM (build.prop reports gracerlte SM-N935F and the device is visible as an SM-N935F on Google Play)

FreeDcam Version:
-----------------
Latest (4.2)

Problem Description:
--------------------
This isn't a bug in the app itself, just a thing I found odd about the play store listing itself. According to the play store listing, my device is not supported, despite the app fully working when installed from F-Droid (including manual controls in camera1 api, which means that Samsung vendor extensions are supported). My Samsung Galaxy S5 (SM-G900F) is listed as not compatible too, but I haven't been able to verify if the app works there yet. All of my other devices are listed as compatible, including a Philips Android TV, that is not physically capable of having a camera.

**Comment by KillerInk** [comment]
Hi
i think it is because of the missing raw support and bad ratings on play from that device.
if something is not fixable due vendor limits, it get disabled.
sometimes people forget that its opensource and ad free.

fdroid and play have the same version. fdroid is just signed by their own key.
the play version can get downloaded here too. 

funny that the tv get listed. normaly it should not be visible, because it need the camera permission
